/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

/**
 *
 * @author nguye
 */
import com.mysql.cj.jdbc.Blob;
import com.mysql.cj.jdbc.result.ResultSetFactory;
import com.sun.jdi.connect.spi.Connection;
import connection.myconnection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

public class signup extends javax.swing.JFrame {
myconnection con = new myconnection();
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ResPassword = new javax.swing.JPasswordField();
        sdt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        signup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        signin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        iduser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/herbal (1).png"))); // NOI18N
        jLabel1.setText("Medicine Flare");
        user.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Đăng Ký");
        user.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên đăng nhập");
        user.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Mật khẩu");
        user.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 215, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nhập lại mật khẩu");
        user.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 277, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");
        user.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 339, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Số điện thoại");
        user.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 401, -1, -1));
        user.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 173, 290, 30));
        user.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 365, 290, 30));

        Password.setMinimumSize(new java.awt.Dimension(64, 30));
        user.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 241, 290, 30));
        user.add(ResPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 303, 290, 30));
        user.add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 427, 290, 30));

        jRadioButton1.setText("Chấp nhận điều khoản của công ty");
        user.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        signup.setBackground(new java.awt.Color(233, 243, 254));
        signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(0, 163, 255));
        signup.setText("Đăng Ký");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        user.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 290, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(123, 123, 123));
        jLabel9.setText("Bạn đã có tài khoản?");
        user.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        signin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signin.setForeground(new java.awt.Color(63, 118, 215));
        signin.setText("Đăng nhập");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        user.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ID");
        user.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 20, 20));

        iduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iduserActionPerformed(evt);
            }
        });
        user.add(iduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 71, -1));

        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backgroup.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
       String id = iduser.getText();
       String ten = user1.getText();
       String pass = Password.getText();
       String email1=email.getText();
       String sdt1=sdt.getText();
       String rePass = ResPassword.getText(); // Giả sử bạn có trường nhập lại mật khẩu

    if (ten.isEmpty() || pass.isEmpty() || rePass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
        return;
    }

    if (!pass.equals(rePass)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!");
        return;
    }

    try {
        // Kiểm tra xem username đã tồn tại chưa
        String checkSql = "SELECT * FROM user WHERE user = ?";
        PreparedStatement checkPs = con.getconnect().prepareStatement(checkSql);
        checkPs.setString(1, ten);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại. Vui lòng chọn tên khác!");
            rs.close();
            checkPs.close();
            return;
        }
        rs.close();
        checkPs.close();

        // Thêm người dùng mới
        String insertSql = "INSERT INTO user  VALUES (?,?,?,?,?)";
        PreparedStatement insertPs = con.getconnect().prepareStatement(insertSql);
        insertPs.setString(1, id);
        insertPs.setString(2, ten);
        insertPs.setString(3, pass);
        insertPs.setString(4, email1);
        insertPs.setString(5, sdt1);

        int affectedRows = insertPs.executeUpdate();

        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
            this.dispose(); // Đóng MainFrame hiện tại
            UserDashboard productFrame1 = new UserDashboard();
            productFrame1.setVisible(true); // Mở ProductFrame
        } else {
            JOptionPane.showMessageDialog(this, "Đăng ký thất bại. Vui lòng thử lại.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }

    }//GEN-LAST:event_signupActionPerformed

    private void iduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iduserActionPerformed

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        this.dispose();
        Login login1 = new Login();
        login1.setVisible(true);
    }//GEN-LAST:event_signinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField ResPassword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField iduser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField sdt;
    private javax.swing.JLabel signin;
    private javax.swing.JButton signup;
    private javax.swing.JPanel user;
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
